### ISSUE TITLE
MakeMeAnAdmin/MakeMeAnAdmin.sh is temp admin access ?

### ISSUE THREAD

**Issue by mani2care** [Rocketman-Tech/MakeMeAnAdmin#1]
MakeMeAnAdmin/MakeMeAnAdmin.sh is temp admin access ?

how to grant permanent access for the mac? with this policy ?

**Comment by geekquixotic** [comment]
While we are always happy to share scripts and processes once they are tested and stable, I can't easily create a one-off workflow without a deeper understanding of the situation. I would hate to make assumptions and end up creating a script/workflow that doesn't solve your problem or, worse yet, creates additional ones.

If you would like to meet with us and see if it would be a good fit to have us develop something for you, let me know how best to contact you and I'll get it to the right person in the office.

**Comment by geekquixotic** [comment]
Since this 'issue' doesn't really pertain to the operation of the script as it is designed, I'll plan to close it at the end of the week. I'll leave it open for any additional communication until then.

**Comment by geekquixotic** [comment]
Closing.
